import type { Metadata } from 'next';
import './globals.css';
import StyledComponentsRegistry from './lib/registry';

export const metadata: Metadata = {
    title: '모던월드',
    description: 'Generated by create next app',
    icons: 'https://wang0514.s3.ap-northeast-2.amazonaws.com/page/power.png',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <StyledComponentsRegistry>
                <body>{children}</body>
            </StyledComponentsRegistry>
        </html>
    );
}
